license="${mod_license}"
issueTrackerURL="https://github.com/Footdablit2310/FootDiscordMC/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

authors="Footdablit2310"

description='''
This mod adds well integration with my discord bot FootBot
'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="*"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
# FootLib
[[dependencies.${mod_id}]]
    modId="footlib"
    type="required"
    versionRange="[${footlib_version}, 1.0.0.0)"
    ordering="NONE"
    side="BOTH"
